=== travismills82/nt5src/inetsrv/uddi/extensions.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="urn:uddi-microsoft-com:api_v2_extensions" xmlns:uddi="urn:uddi-org:api_v2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:uddi-microsoft-com:api_v2_extensions" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="urn:uddi-org:api_v2" schemaLocation="http://www.uddi.org/schema/uddi_v2.xsd" />
	<xs:complexType name="categoryValueType">
		<xs:attribute name="tModelKey" type="xs:string" use="optional" />
		<xs:attribute name="keyName" type="xs:string" use="optional" />
		<xs:attribute name="keyValue" type="xs:string" use="optional" />
		<xs:attribute name="parentKeyValue" type="xs:string" use="optional" />
		<xs:attribute name="isValid" type="xs:boolean" use="optional" />
	</xs:complexType>
	<xs:simpleType name="relationshipQualifiersType" final="list">
		<xs:restriction base="xs:string">
			<xs:enumeration value="root" />
			<xs:enumeration value="parent" />
			<xs:enumeration value="child" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="get_relatedCategories">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="category" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="relationshipQualifier" type="relationshipQualifiersType" minOccurs="0" maxOccurs="unbounded" />
						</xs:sequence>
						<xs:attribute name="tModelKey" type="xs:string" use="required" />
						<xs:attribute name="keyValue" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="categoryList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="categoryInfo" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="truncated" type="uddi:truncated" use="optional" />
			<xs:attribute name="operator" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="categoryValue" type="categoryValueType" />
	<xs:element name="categoryInfo">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="categoryValueType">
					<xs:sequence>
						<xs:element name="rootRelationship" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element ref="categoryValue" minOccurs="0" maxOccurs="unbounded" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="parentRelationship" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element ref="categoryValue" minOccurs="0" maxOccurs="unbounded" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="childRelationship" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element ref="categoryValue" minOccurs="0" maxOccurs="unbounded" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="resources">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="categorizationSchemes" minOccurs="0" />
				<xs:element ref="uddi:tModelDetail" minOccurs="0" />
				<xs:element ref="uddi:businessDetail" minOccurs="0" />
				<xs:element ref="uddi:serviceDetail" minOccurs="0" />
				<xs:element ref="uddi:bindingDetail" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="categorizationSchemes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="categorizationScheme" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="categorizationScheme">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="uddi:tModel" />
					<xs:element ref="tModelKey" />
				</xs:choice>
				<xs:element name="categoryValue" type="categoryValueType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="checked" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="tModelKey" type="xs:string" />
</xs:schema>

=== travismills82/nt5src/inetsrv/uddi/setup/bootstrap/public/production/09.ntis-gov-sic-1987.microsoft.bootstrap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ############################################################################ -->
<!-- ## UDDI Services                                                          ## -->
<!-- ## Copyright (c) Microsoft Corporation.  All rights reserved.             ## -->
<!-- ############################################################################ -->
<!-- 
Date: 24 January 2002
Name: 15.microsoft-com-geoweb-2000.microsoft.bootstrap.xml
Version: 1.0
Description: Microsoft Geoweb 2000 geographic taxonomy
Resource File Dependencies: 
	01.uddi-org-types.ibm.bootstrap.xml
Reference: http://www.microsoft.com
Terms of Use: See the Microsoft Windows .NET Server 2003 family end-user license agreement.
-->
<resources xmlns="urn:uddi-microsoft-com:api_v2_extensions" xmlns:uddi="urn:uddi-org:api_v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:microsoft-com:api_v2_extensions
extensions.xsd">
	<categorizationSchemes>
		<categorizationScheme checked="false">
			<tModelKey>uuid:70A80F61-77BC-4821-A5E2-2A406ACC35DD</tModelKey>
			<categoryValue keyName="Agriculture, Forestry, and Fishing" keyValue="0" parentKeyValue="" isValid="false"/>
			<categoryValue keyName="Mining" keyValue="10" parentKeyValue="" isValid="true"/>
			<categoryValue keyName="Agricultural Production - Crops" keyValue="100" parentKeyValue="0" isValid="true"/>
			<categoryValue keyName="Metal Mining" keyValue="1000" parentKeyValue="10" isValid="true"/>
			<categoryValue keyName="Iron Ores" keyValue="1010" parentKeyValue="1000" isValid="true"/>
			<categoryValue keyName="Iron ores" keyValue="1011" parentKeyValue="1010" isValid="true"/>
			<categoryValue keyName="Copper Ores" keyValue="1020" parentKeyValue="1000" isValid="true"/>
			<categoryValue keyName="Copper ores" keyValue="1021" parentKeyValue="1020" isValid="true"/>
			<categoryValue keyName="Lead and Zinc Ores" keyValue="1030" parentKeyValue="1000" isValid="true"/>
			<categoryValue keyName="Lead and zinc ores" keyValue="1031" parentKeyValue="1030" isValid="true"/>
			<categoryValue keyName="Gold and Silver Ores" keyValue="1040" parentKeyValue="1000" isValid="true"/>
			<categoryValue keyName="Gold ores" keyValue="1041" parentKeyValue="1040" isValid="true"/>
			<categoryValue keyName="Silver ores" keyValue="1044" parentKeyValue="1040" isValid="true"/>
			<categoryValue keyName="Bauxite and other aluminum ores" keyValue="1050" parentKeyValue="1000" isValid="true"/>
			<categoryValue keyName="Bauxite and other aluminum ores" keyValue="1051" parentKeyValue="1050" isValid="true"/>
			<categoryValue keyName="Ferroalloy Ores, Except Vanadium" keyValue="1060" parentKeyValue="1000" isValid="true"/>
			<categoryValue keyName="Ferroalloy ores, except vanadium" keyValue="1061" parentKeyValue="1060" isValid="true"/>
			<categoryValue keyName="Metal Mining Services" keyValue="1080" parentKeyValue="1000" isValid="true"/>
			<categoryValue keyName="Metal mining services" keyValue="1081" parentKeyValue="1080" isValid="true"/>
			<categoryValue keyName="Miscellaneous Metal Ores" keyValue="1090" parentKeyValue="1000" isValid="true"/>
			<categoryValue keyName="Mercury ores" keyValue="1092" parentKeyValue="1090" isValid="true"/>
			<categoryValue keyName="Uranium-radium-vanadium ores" keyValue="1094" parentKeyValue="1090" isValid="true"/>
			<categoryValue keyName="Metal ores, n.e.c." keyValue="1099" parentKeyValue="1090" isValid="true"/>
			<categoryValue keyName="Cash Grains" keyValue="110" parentKeyValue="100" isValid="true"/>
			<categoryValue keyName="Anthracite mining" keyValue="1100" parentKeyValue="10" isValid="true"/>
			<categoryValue keyName="Wheat" keyValue="111" parentKeyValue="110" isValid="true"/>
			<categoryValue keyName="Anthracite mining" keyValue="1110" parentKeyValue="1100" isValid="true"/>
			<categoryValue keyName="Anthracite" keyValue="1111" parentKeyValue="1110" isValid="true"/>
			<categoryValue keyName="Anthracite mining services" keyValue="1112" parentKeyValue="1110" isValid="true"/>
			<categoryValue keyName="Rice" keyValue="112" parentKeyValue="110" isValid="true"/>
			<categoryValue keyName="Corn" keyValue="115" parentKeyValue="110" isValid="true"/>
			<categoryValue keyName="Soybeans" keyValue="116" parentKeyValue="110" isValid="true"/>
			<categoryValue keyName="Cash grains, n.e.c." keyValue="119" parentKeyValue="110" isValid="true"/>
			<categoryValue keyName="Bituminous coal and lignite mining" keyValue="1200" parentKeyValue="10" isValid="true"/>
			<categoryValue keyName="Bituminous coal and lignite mining" keyValue="1210" parentKeyValue="1200" isValid="true"/>
			<categoryValue keyName="Bituminous coal and lignite" keyValue="1211" parentKeyValue="1210" isValid="true"/>
			<categoryValue keyName="Bituminous &amp; lignite mining services" keyValue="1213" parentKeyValue="1210" isValid="true"/>
			<categoryValue keyName="Bituminous coal and lignite mining" keyValue="1220" parentKeyValue="1200" isValid="true"/>
			<categoryValue keyName="Bituminous coal and lignite surface" keyValue="1221" parentKeyValue="1220" isValid="true"/>
			<categoryValue keyName="Bituminous coal underground" keyValue="1222" parentKeyValue="1220" isValid="true"/>
			<categoryValue keyName="Anthracite mining" keyValue="1230" parentKeyValue="1200" isValid="true"/>
			<categoryValue keyName="Anthracite mining" keyValue="1231" parentKeyValue="1230" isValid="true"/>
			<categoryValue keyName="Coal mining services" keyValue="1240" parentKeyValue="1200" isValid="true"/>
			<categoryValue keyName="Coal mining services" keyValue="1241" parentKeyValue="1240" isValid="true"/>
			<categoryValue keyName="Field Crops, Except Cash Grains" keyValue="130" parentKeyValue="100" isValid="true"/>
			<categoryValue keyName="Oil and Gas Extraction" keyValue="1300" parentKeyValue="10" isValid="true"/>
			<categoryValue keyName="Cotton" keyValue="131" parentKeyValue="130" isValid="true"/>
			<categoryValue keyName="Crude Petroleum and Natural Gas" keyValue="1310" parentKeyValue="1300" isValid="true"/>
			<categoryValue keyName="Crude petroleum and natural gas" keyValue="1311" parentKeyValue="1310" isValid="true"/>
			<categoryValue keyName="Tobacco" keyValue="132" parentKeyValue="130" isValid="true"/>
			<categoryValue keyName="Natural Gas Liquids" keyValue="1320" parentKeyValue="1300" isValid="true"/>
			<categoryValue keyName="Natural gas liquids" keyValue="1321" parentKeyValue="1320" isValid="true"/>
			<categoryValue keyName="Sugarcane and sugar beet" keyValue="133" parentKeyValue="130" isValid="true"/>
			<categoryValue keyName="Irish potatoes" keyValue="134" parentKeyValue="130" isValid="true"/>
			<categoryValue keyName="Oil and Gas Field Services" keyValue="1380" parentKeyValue="1300" isValid="true"/>
			<categoryValue keyName="Drilling oil and gas wells" keyValue="1381" parentKeyValue="1380" isValid="true"/>
			<categoryValue keyName="Oil and gas exploration services" keyValue="1382" parentKeyValue="1380" isValid="true"/>
			<categoryValue keyName="Oil and gas field services, n.e.c." keyValue="1389" parentKeyValue="1380" isValid="true"/>
			<categoryValue keyName="Field crops, except cash grains, n.e.c." keyValue="139" parentKeyValue="130" isValid="true"/>
			<categoryValue keyName="Nonmetallic Minerals, Except Fuels" keyValue="1400" parentKeyValue="10" isValid="true"/>
			<categoryValue keyName="Dimension Stone" keyValue="1410" parentKeyValue="1400" isValid="true"/>
			<categoryValue keyName="Dimension stone" keyValue="1411" parentKeyValue="1410" isValid="true"/>
			<categoryValue keyName="Crushed and Broken Stone" keyValue="1420" parentKeyValue="1400" isValid="true"/>
			<categoryValue keyName="Crushed and broken limestone" keyValue="1422" parentKeyValue="1420" isValid="true"/>
			<categoryValue keyName="Crushed and broken granite" keyValue="1423" parentKeyValue="1420" isValid="true"/>
			<categoryValue keyName="Crushed and broken stone, n.e.c." keyValue="1429" parentKeyValue="1420" isValid="true"/>
			<categoryValue keyName="Sand and Gravel" keyValue="1440" parentKeyValue="1400" isValid="true"/>
			<categoryValue keyName="Construction sand and gravel" keyValue="1442" parentKeyValue="1440" isValid="true"/>
			<categoryValue keyName="Industrial sand" keyValue="1446" parentKeyValue="1440" isValid="true"/>
			<categoryValue keyName="Clay, Ceramic &amp; Refractory Minerals" keyValue="1450" parentKeyValue="1400" isValid="true"/>
			<categoryValue keyName="Bentonite" keyValue="1452" parentKeyValue="1450" isValid="true"/>
			<categoryValue keyName="Fire clay" keyValue="1453" parentKeyValue="1450" isValid="true"/>
			<categoryValue keyName="Fuller's earth" keyValue="1454" parentKeyValue="1450" isValid="true"/>
			<categoryValue keyName="Kaolin and ball clay" keyValue="1455" parentKeyValue="1450" isValid="true"/>
			<categoryValue keyName="Clay and related minerals, n.e.c." keyValue="1459" parentKeyValue="1450" isValid="true"/>
			<categoryValue keyName="Chemical and Fertilizer Minerals" keyValue="1470" parentKeyValue="1400" isValid="true"/>
			<categoryValue keyName="Barite" keyValue="1472" parentKeyValue="1470" isValid="true"/>
			<categoryValue keyName="Fluorspar" keyValue="1473" parentKeyValue="1470" isValid="true"/>
			<categoryValue keyName="Potash, soda, and borate minerals" keyValue="1474" parentKeyValue="1470" isValid="true"/>
			<categoryValue keyName="Phosphate rock" keyValue="1475" parentKeyValue="1470" isValid="true"/>
			<categoryValue keyName="Rock salt" keyValue="1476" parentKeyValue="1470" isValid="true"/>
			<categoryValue keyName="Sulfur" keyValue="1477" parentKeyValue="1470" isValid="true"/>
			<categoryValue keyName="Chemical and fertilizer mining, n.e.c." keyValue="1479" parentKeyValue="1470" isValid="true"/>
			<categoryValue keyName="Nonmetallic Minerals Services" keyValue="1480" parentKeyValue="1400" isValid="true"/>
